In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'customer_id': [1, 2, 3, 4, 2, 5],
    'age': [25, np.nan, 35, np.nan, np.nan, 40],
    'city': ['Mumbai', 'Delhi', np.nan, 'Mumbai', 'Delhi', np.nan],
    'gender': ['Male', 'Female', 'Female', 'Male', 'Female', 'Male'],
    'annual_income': [40000, 80000, 60000, 120000, 80000, 95000]
})

df

   customer_id   age    city  gender  annual_income
0            1  25.0  Mumbai    Male          40000
1            2   NaN   Delhi  Female          80000
2            3  35.0     NaN  Female          60000
3            4   NaN  Mumbai    Male         120000
4            2   NaN   Delhi  Female          80000
5            5  40.0     NaN    Male          95000

In [2]:
# Fill missing values
df['age'] = df['age'].fillna(df['age'].median())
df['city'] = df['city'].fillna(df['city'].mode()[0])

# Remove duplicates
df = df.drop_duplicates()

print("After cleaning:")
df

After cleaning:

   customer_id   age    city  gender  annual_income
0            1  25.0  Mumbai    Male          40000
1            2  35.0   Delhi  Female          80000
2            3  35.0   Delhi  Female          60000
3            4  35.0  Mumbai    Male         120000
5            5  40.0   Delhi    Male          95000

In [3]:

# One-Hot Encoding for city
df = pd.get_dummies(df, columns=['city'])

# Label Encoding for gender
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['gender'] = le.fit_transform(df['gender'])

print("After encoding:")
df

After encoding:

   customer_id   age  gender  annual_income  city_Delhi  city_Mumbai
0            1  25.0       1          40000       False         True
1            2  35.0       0          80000        True        False
2            3  35.0       0          60000        True        False
3            4  35.0       1         120000       False         True
5            5  40.0       1          95000        True        False

In [4]:

from sklearn.preprocessing import MinMaxScaler, StandardScaler

# Min-Max Scaling
minmax = MinMaxScaler()
df_minmax = df.copy()
df_minmax[['age', 'annual_income']] = minmax.fit_transform(df[['age', 'annual_income']])

print("Min-Max Scaling:")
print(df_minmax)

# Standard Scaling
scaler = StandardScaler()
df_standard = df.copy()
df_standard[['age', 'annual_income']] = scaler.fit_transform(df[['age', 'annual_income']])

print("\nStandard Scaling:")
print(df_standard)

Min-Max Scaling:
   customer_id       age  gender  annual_income  city_Delhi  city_Mumbai
0            1  0.000000       1         0.0000       False         True
1            2  0.666667       0         0.5000        True        False
2            3  0.666667       0         0.2500        True        False
3            4  0.666667       1         1.0000       False         True
5            5  1.000000       1         0.6875        True        False

Standard Scaling:
   customer_id       age  gender  annual_income  city_Delhi  city_Mumbai
0            1 -1.837117       1      -1.410970       False         True
1            2  0.204124       0       0.036179        True        False
2            3  0.204124       0      -0.687396        True        False
3            4  0.204124       1       1.483328       False         True
5            5  1.224745       1       0.578860        True        False

In [5]:
print("""
Min-Max Scaling scales data between 0 and 1 and is useful when features need a fixed range.
Standardization transforms data to have mean 0 and standard deviation 1, which is better for algorithms assuming normal distribution.
""")

Min-Max Scaling scales data between 0 and 1 and is useful when features need a fixed range.
Standardization transforms data to have mean 0 and standard deviation 1, which is better for algorithms assuming normal distribution.